{"name": "система вернёт ошибку, если неправильно указать поле: login", "status": "passed", "description": "если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'неверный логин/пароль', 'password': 'dytkfdfkkwnxyoxcktdqjhdntifoarwzsuvoclvrqfarmhvizasqewscounrgzvbgsuvqcwfkgigfxpqlsyixbdndmzeyygubbmv'}"}], "start": 1733681767103, "stop": 1733681767283}], "parameters": [{"name": "invalid_data_fields", "value": "'login'"}], "start": 1733681767103, "stop": 1733681767283, "uuid": "cc7cf703-b750-4981-80c5-3d744d329b30", "historyId": "4c9cd0a9df13bba22c27258be7816db3", "testCaseId": "5e7a8ed2e7ddfa7c8c95b1ddf06c09cf", "fullName": "tests.test_login_courier.TestLoginCourier#test_invalid_data_login_courier_error_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "ESHLENDER"}, {"name": "thread", "value": "14076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}