{"name": "система вернёт ошибку, если неправильно указать поле: password", "status": "passed", "description": "если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'gsblhmwzulncuhqxddaozqpykizwcvkmbbowgvqgirityilsixzqtputhrjctrgiqprbpngmuqpvbiuvghlkvtxldjokfqkptxht', 'password': 'неверный логин/пароль'}"}], "start": 1733681767461, "stop": 1733681767595}], "parameters": [{"name": "invalid_data_fields", "value": "'password'"}], "start": 1733681767461, "stop": 1733681767595, "uuid": "f58855f3-485b-43c5-b490-aa3c5dda0e6e", "historyId": "ac98430753fdda3aad973f61a73e8635", "testCaseId": "5e7a8ed2e7ddfa7c8c95b1ddf06c09cf", "fullName": "tests.test_login_courier.TestLoginCourier#test_invalid_data_login_courier_error_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "ESHLENDER"}, {"name": "thread", "value": "14076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}